### ISSUE TITLE
Inspector needs to find a maximum `q`

### ISSUE THREAD

**Issue by nrryuya** [LayerXcom/safety-oracle#14]

**Comment by minaminao** [comment]
Strictly, the Inspector needs to finding a maximum t.
![WolframAlpha--Plot3D__1_2___k___2q_100____k__1__10____q__50__100________2019_09_18_01_35](https://user-images.githubusercontent.com/20497787/65121371-0d695800-da2a-11e9-93a0-c651f1b7bcb2.png)
